FROM ubuntu:focal
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3.8 libpython3.8-testsuite && \
    apt clean

COPY internalerror.py /
RUN python3.8 /internalerror.py
